bookapp/config/routes.rb
Rails.application.routes.draw do
  root to: 'books#index'
  resources :books
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

bookapp/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

bookapp/app/models/book.rb
class Book < ApplicationRecord
  has_many :comments, dependent: :destroy, inverse_of: :book
  has_many :quotations, dependent: :destroy, inverse_of: :book

  accepts_nested_attributes_for :comments, reject_if: :all_blank, allow_destroy: true
  accepts_nested_attributes_for :quotations, reject_if: :all_blank, allow_destroy: true

  validates :title, presence: true
  validates :price, presence: true
  validates :rate, presence: true
end

bookapp/app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :book

  validates :name, presence: true
  validates :content, presence: true
end

bookapp/app/models/quotation.rb
class Quotation < ApplicationRecord
  belongs_to :book

  validates :body, presence: true
end

bookapp/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

bookapp/app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action:set_book, only: [:show, :edit, :update, :destroy]

  def index
    @book = Book.all
  end

  def new
    @book = Book.new
  end

  def create
    @book = Book.new(book_params)
    if @book.save
      redirect_to root_path
    else
      render new_book_path
    end
  end

  def show
  end

  def edit
  end

  def update
    @book.update(book_params)
    redirect_to edit_book_path(@book.id)
  end

  def destroy
    @book.destroy
    redirect_to root_path
  end

  private

  def book_params
    params.require(:book).permit(
      :title, :price, :description, :rate,
      comments_attributes: [:id, :name, :content, :_destroy],
      quotations_attributes: [:id, :body,:_destroy]
  )
  end

  def set_book
    @book = Book.find(params[:id])
  end
end

bookapp/app/helpers/application_helper.rb
module ApplicationHelper
end

bookapp/app/helpers/books_helper.rb
module BooksHelper
end

bookapp/app/helpers/comments_helper.rb
module CommentsHelper
end

bookapp/app/helpers/quotations_helper.rb
module QuotationsHelper
end

bookapp/app/views/books/_comment_fields.html.erb
<div class="nested-fields">
  <div class="field">
    <%= f.label "投稿者　" %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label "コメント" %>
    <%= f.text_field :content %>
  </div>

  <%= link_to_remove_association "コメントを削除します", f %>
</div>

bookapp/app/views/books/_form.html.erb
<%= form_for @book do |f| %>
  <div class="field">
    <%= f.label :title %>
    <br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :price %>
    <br>
    <%= f.text_field :price %>
  </div>
  <div class="field">
    <%= f.label :description %>
    <br>
    <%= f.text_field :description %>
  </div>
  <div class="field">
    <%= f.label :rate %>
    <br>
    <%= f.text_field :rate %>
  </div>


  <h3>引用</h3>

  <div id="quotations">
    <%= f.fields_for :quotations do |quotation| %>
      <%= render 'quotation_fields', f: quotation %>
      <a>-----------------------------------------</a>
    <% end %>
    <div class="links">
      <%= link_to_add_association '引用を追加します', f, :quotations %>
    </div>
  </div>


  <h3>コメント</h3>

  <div id="comments">
    <%= f.fields_for :comments do |comment| %>
      <%= render 'comment_fields', f: comment %>
      <a>-----------------------------------------</a>
    <% end %>
    <div class="links">
      <%= link_to_add_association 'コメントを追加します', f, :comments %>
    </div>
  </div>

  <%= f.submit %>

<% end %>

bookapp/app/views/books/_quotation_fields.html.erb
<div class="nested-fields">
  <div class="field">
    <%= f.label "引用" %>
    <%= f.text_field :body %>
  </div>

  <%= link_to_remove_association "引用を削除します", f %>
</div>

bookapp/app/views/books/_show_comment_fields.html.erb
<div class="nested-fields">
  <div class="field">
    <%= f.label "投稿者　" %>

    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label "コメント" %>

    <%= f.text_field :content %>
  </div>
</div>

bookapp/app/views/books/_show_form.html.erb
<%= form_for @book do |f| %>

  <h3>引用</h3>
  <div id="quotations">
    <%= f.fields_for :quotations do |quotation| %>
      <%= render 'show_quotation_fields', f: quotation %>
      <a>-----------------------------------------</a>
    <% end %>
    <div class="links">
      <%= link_to_add_association '引用を追加します', f, :quotations %>
    </div>
  </div>

  <h3>コメント</h3>
  <div id="comments">
    <%= f.fields_for :comments do |comment| %>
      <%= render 'show_comment_fields', f: comment %>
      <a>-----------------------------------------</a>
    <% end %>
    <div class="links">
      <%= link_to_add_association 'コメントを追加します', f, :comments %>
    </div>
  </div>
  <br>
  <%= f.submit %>

<% end %>

bookapp/app/views/books/_show_quotation_fields.html.erb
<div class="nested-fields">
  <div class="field">
    <%= f.label "引用　" %>

    <%= f.text_field :body %>
  </div>
</div>

bookapp/app/views/books/edit.html.erb
<h1>管理画面</h1>
<p style="color: red;">※更新・削除処理を確定するにはページ最下部の「Update Book」を押してください。</p>

<%= render 'form' %>

<p><%= link_to "本を削除する", book_path(@book.id),method: :delete, data: { confirm: "削除しますか？"} %></p>

<p><%= link_to "Home", root_path %></p>

bookapp/app/views/books/index.html.erb
<h1>本の一覧</h1>

<% @book.each do |book| %>
<h2>題名：<%= book.title %></h2>
<p><%= link_to "詳細ページはこちら" , book_path(book.id) %></p>
<p><%= link_to "管理画面はこちら" , edit_book_path(book.id) %></p>
<hr>
<% end %>
<p><%= link_to "新規作成ページへ", new_book_path %></p>

bookapp/app/views/books/new.html.erb
<h1>新しい本の登録</h1>
<p>必要事項を記入して新しく本を登録してください</p>


<%= render 'form' %>



<p><%= link_to "Home", root_path %></p>

bookapp/app/views/books/show.html.erb
<h1>詳細ページ</h1>
<h2>題名：<%= @book.title %></h2>
<p>価格：<%= @book.price %>円</p>
<p>説明：<%= @book.description %></p>
<p>評価：<%= @book.rate %></p>

<hr>


<!-- ーーーーここからコメントーーーーーーーーーーーーーー -->
<p style="color: red;">※引用・コメント追加を確定するにはページ最下部の「Update Book」を押してください。</p>
<%= render 'show_form' %>

<p><%= link_to "Home", root_path %></p>

bookapp/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookapp</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>